# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0002_auto_20170328_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
