# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0003_auto_20170328_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_active',
        ),
    ]
