# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0005_auto_20170328_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='language',
            field=models.CharField(default='python', max_length=10),
            preserve_default=False,
        ),
    ]
