# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0006_answer_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='age',
        ),
    ]
