# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0007_remove_answer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='percent_match',
            field=models.IntegerField(default=88),
            preserve_default=False,
        ),
    ]
