# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0010_auto_20170329_1702'),
        ('dating_app', '0010_image'),
    ]

    operations = [
    ]
