# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0011_merge_20170329_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='feet',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='inches',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='height',
            field=models.FloatField(),
        ),
    ]
