# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0013_auto_20170329_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile_pic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_pic', to='dating_app.User'),
        ),
    ]
