# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0014_auto_20170330_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('feet', models.IntegerField()),
                ('inches', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
                ('zip_code', models.IntegerField()),
                ('stack', models.CharField(max_length=15)),
                ('religion', models.CharField(max_length=10)),
                ('smoke', models.BooleanField(default=False)),
                ('body_type', models.CharField(max_length=20)),
                ('ethnicity', models.CharField(max_length=20)),
                ('wants_children', models.BooleanField()),
                ('about_you', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_preferences', to='dating_app.User')),
            ],
        ),
    ]
