# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0014_auto_20170330_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic_url',
            field=models.CharField(default='img/user.png', max_length=100),
        ),
    ]
