# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0015_user_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.FileField(default='img/user.png', upload_to='img'),
        ),
    ]
