# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0017_merge_20170330_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_conversation1', to='dating_app.User')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_conversation2', to='dating_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dating_app.Conversation'),
            preserve_default=False,
        ),
    ]
